name: lego_app
description: App de gestão de coleção Lego (stock, compras, vendas, dashboard).
publish_to: 'none'
version: 2.5.0+30

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: # <-- ADICIONA ISTO
    sdk: flutter              # <-- E ISTO


  package_info_plus: ^10.2.1
  google_fonts: ^6.1.0 # Para a fonte Varela Round (parecida com a da LEGO)

  # Base de dados local (reativa, tipada)
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.4
  path: ^1.9.0

  # Gestão de estado (liga a UI aos streams do Drift)
  flutter_riverpod: ^3.3.2

  barcode_widget: ^2.0.4 #Para gerar o barcode do cartão da lego!

  screen_brightness: ^2.0.0

  rxdart: ^0.28.0

  # Import / export de .xlsx
  excel: ^4.0.6
  file_selector: ^1.0.3
  share_plus: ^13.2.1  # <-- Atualizado para suportar Built-in Kotlin

  # Gráficos do dashboard
  fl_chart: ^1.2.0

  # Datas
  intl: ^0.20.2

  # Ids únicos para os registos
  uuid: ^4.6.0

  cupertino_icons: ^1.0.8

  shared_preferences: ^2.5.5
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  cloud_firestore: ^6.7.1
  google_sign_in: ^7.2.0
  connectivity_plus: ^7.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  # Ferramenta para gerar o ícone da app (deve estar em dev_dependencies)
  flutter_launcher_icons: ^0.14.4

  # Geração de código do Drift
  build_runner: ^2.4.13
  drift_dev: ^2.20.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/piece.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/lego_minifig.png
    - assets/lego.png
    - assets/google.png
    - assets/piece.png
    - assets/insiders.png